import { ShopItem } from '../logic/types';

export const SHOP_ITEMS: ShopItem[] = [
  // 4 Обязательных товара (Нужно)
  {
    id: 'food_nutritious',
    name: 'Питательный сухой корм',
    price: 80,
    category: 'mandatory',
    categoryName: 'Нужно',
    description: 'Вкусный и полезный рацион. Дарит Финни много сил и энергии.',
    icon: '🥣',
    hungerBonus: 40,
    moodBonus: 10,
    careBonus: 15,
  },
  {
    id: 'vitamins_pack',
    name: 'Витаминный комплекс',
    price: 60,
    category: 'mandatory',
    categoryName: 'Нужно',
    description: 'Витамины укрепляют иммунитет питомца и его здоровье.',
    icon: '💊',
    hungerBonus: 10,
    moodBonus: 15,
    careBonus: 35,
  },
  {
    id: 'vet_checkup',
    name: 'Осмотр у доктора',
    price: 120,
    category: 'mandatory',
    categoryName: 'Нужно',
    description: 'Плановый визит к ветеринару. Гарантирует отличное самочувствие.',
    icon: '🩺',
    hungerBonus: 0,
    moodBonus: 10,
    careBonus: 45,
  },
  {
    id: 'hygiene_shampoo',
    name: 'Эко-шампунь и расчёска',
    price: 70,
    category: 'mandatory',
    categoryName: 'Нужно',
    description: 'Бережный уход за шерсткой. Питомец чистый и ухоженный.',
    icon: '🧼',
    hungerBonus: 0,
    moodBonus: 20,
    careBonus: 30,
  },

  // 5 Необязательных товаров (Хочу)
  {
    id: 'toy_mouse',
    name: 'Заводная мышка-игрушка',
    price: 90,
    category: 'optional',
    categoryName: 'Хочу',
    description: 'Весёлая заводная игрушка для активных игр с Финни.',
    icon: '🐭',
    hungerBonus: 0,
    moodBonus: 35,
    careBonus: 5,
  },
  {
    id: 'treat_sweet',
    name: 'Сладкое хрустящее лакомство',
    price: 50,
    category: 'optional',
    categoryName: 'Хочу',
    description: 'Вкусняшка для поднятия настроения, но не заменяет основной обед.',
    icon: '🍪',
    hungerBonus: 15,
    moodBonus: 25,
    careBonus: 0,
  },
  {
    id: 'party_hat',
    name: 'Праздничный колпак',
    price: 110,
    category: 'optional',
    categoryName: 'Хочу',
    description: 'Яркий блестящий колпак для веселой домашней вечеринки.',
    icon: '🎉',
    hungerBonus: 0,
    moodBonus: 40,
    careBonus: 0,
  },
  {
    id: 'soft_cushion',
    name: 'Мягкий пушистый лежак',
    price: 140,
    category: 'optional',
    categoryName: 'Хочу',
    description: 'Уютное спальное место для сладких снов питомца.',
    icon: '🛋️',
    hungerBonus: 0,
    moodBonus: 45,
    careBonus: 10,
  },
  {
    id: 'laser_pointer',
    name: 'Лазерная указка с лучиком',
    price: 85,
    category: 'optional',
    categoryName: 'Хочу',
    description: 'Красный лучик, за которым так весело и азартно бегать по комнате!',
    icon: '🔦',
    hungerBonus: 0,
    moodBonus: 30,
    careBonus: 5,
  },
];
